[package]
name = "wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.27"
env_logger = "0.10"
log = "0.4"
wgpu = "0.15"
pollster = "0.3"
bytemuck = { version = "1.13", features = ["derive"] }
image = { version = "0.24", default_features = false, features = [
  "png",
  "jpeg",
] }
